/* This module contains the interactions with the user on the UI which are not generated by the state machines. */


// perform a test scan on the scanners to make the pictures usable and configure them
function testScan() {
    var settings = {
        brightness: getIntValueFromId("settings-brightness"),
        contrast: getIntValueFromId("settings-contrast"),
        dpi: getIntValueFromId("settings-dpi"),
    }
    model.deliverMessage(message("test_scan", {"settings": settings}));
}



